import { GetArrayElementWhichMustExistByPredicateOperation } from "./getArrayElementWhichMustExistByPredicate";
declare const GetArrayElementWhichMustExistByPredicateOperationLocalization__English: GetArrayElementWhichMustExistByPredicateOperation.Localization;
export default GetArrayElementWhichMustExistByPredicateOperationLocalization__English;
