import ModuleDynamicLoadingFailedError from "./ModuleDynamicLoadingFailedError";
declare const ModuleDynamicLoadingFailedErrorLocalization__English: ModuleDynamicLoadingFailedError.Localization;
export default ModuleDynamicLoadingFailedErrorLocalization__English;
