import ClassRequiredInitializationHasNotBeenExecutedError from "./ClassRequiredInitializationHasNotBeenExecutedError";
declare const ClassRequiredInitializationHasNotBeenExecutedErrorLocalization__English: ClassRequiredInitializationHasNotBeenExecutedError.Localization;
export default ClassRequiredInitializationHasNotBeenExecutedErrorLocalization__English;
