import FileReadingFailedError from "./FileReadingFailedError";
declare const FileReadingFailedErrorLocalization__English: FileReadingFailedError.Localization;
export default FileReadingFailedErrorLocalization__English;
