import InvalidParameterValueError from "./InvalidParameterValueError";
declare const InvalidParameterValueErrorLocalization__English: InvalidParameterValueError.Localization;
export default InvalidParameterValueErrorLocalization__English;
