import IncompatiblePropertiesInObjectTypeParameterError from "./IncompatiblePropertiesInObjectTypeParameterError";
declare const IncompatiblePropertiesInObjectTypeParameterErrorLocalization__English: IncompatiblePropertiesInObjectTypeParameterError.Localization;
export default IncompatiblePropertiesInObjectTypeParameterErrorLocalization__English;
