import InterProcessInteractionFailedError from "./InterProcessInteractionFailedError";
declare const InterProcessInteractionFailedErrorLocalization__English: InterProcessInteractionFailedError.Localization;
export default InterProcessInteractionFailedErrorLocalization__English;
