import DataSubmittingFailedError from "./DataSubmittingFailedError";
declare const DataSubmittingFailedErrorLocalization__English: DataSubmittingFailedError.Localization;
export default DataSubmittingFailedErrorLocalization__English;
