"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isUndefined = exports.isNull = exports.isNotNull = exports.Timer = exports.secondsToMilliseconds = void 0;
const secondsToMilliseconds_1 = require("./DateTime/secondsToMilliseconds");
exports.secondsToMilliseconds = secondsToMilliseconds_1.default;
const Timer_1 = require("./DateTime/Timer");
exports.Timer = Timer_1.default;
const isNotNull_1 = require("./TypeGuards/Nullables/isNotNull");
exports.isNotNull = isNotNull_1.default;
const isNull_1 = require("./TypeGuards/Nullables/isNull");
exports.isNull = isNull_1.default;
const isUndefined_1 = require("./TypeGuards/Nullables/isUndefined");
exports.isUndefined = isUndefined_1.default;
