import InvalidExternalDataError from "./InvalidExternalDataError";
export declare const InvalidExternalDataErrorLocalization__English: InvalidExternalDataError.Localization;
export default InvalidExternalDataErrorLocalization__English;
