extends: ./node_modules/@yamato-daiwa/style_guides/ECMAScript.js

parserOptions:

  project: "./tsconfig.eslint.json"


overrides:

  - files: [ "Tests/Manual/**/*.ts" ]
    rules:

      # Because it is the manual tests and we need the feedback
      "no-console": off
