import CrossBrowserIssueError from "./CrossBrowserIssueError";
declare const CrossBrowserIssueErrorLocalization__English: CrossBrowserIssueError.Localization;
export default CrossBrowserIssueErrorLocalization__English;
