extends: ./node_modules/@yamato-daiwa/style_guides/ECMAScript.js


parserOptions:

  project: "./tsconfig.eslint.json"


rules:

  # The Node.js version limitations is not applicable to this package for BrowserJS
  node/no-unsupported-features/es-syntax: off
